local opts = { noremap=true }
vim.api.nvim_set_keymap('n', '<leader>m', '<cmd>lua require("harpoon.ui").toggle_quick_menu()<CR>', opts)
vim.api.nvim_set_keymap('n', '<leader>a', '<cmd>lua require("harpoon.mark").add_file()<CR>', opts)
vim.api.nvim_set_keymap('n', '<leader>1', '<cmd>lua require("harpoon.ui").nav_file(1)<CR>', opts)
vim.api.nvim_set_keymap('n', '<leader>2', '<cmd>lua require("harpoon.ui").nav_file(2)<CR>', opts)
vim.api.nvim_set_keymap('n', '<leader>3', '<cmd>lua require("harpoon.ui").nav_file(3)<CR>', opts)
vim.api.nvim_set_keymap('n', '<leader>4', '<cmd>lua require("harpoon.ui").nav_file(4)<CR>', opts)
vim.api.nvim_set_keymap('n', '<leader>5', '<cmd>lua require("harpoon.ui").nav_file(5)<CR>', opts)
vim.api.nvim_set_keymap('n', '<leader>6', '<cmd>lua require("harpoon.ui").nav_file(6)<CR>', opts)
vim.api.nvim_set_keymap('n', '<leader>7', '<cmd>lua require("harpoon.ui").nav_file(7)<CR>', opts)
vim.api.nvim_set_keymap('n', '<leader>8', '<cmd>lua require("harpoon.ui").nav_file(8)<CR>', opts)
vim.api.nvim_set_keymap('n', '<leader>9', '<cmd>lua require("harpoon.ui").nav_file(9)<CR>', opts)
vim.api.nvim_set_keymap('n', '<leader>10', '<cmd>lua require("harpoon.ui").nav_file(10)<CR>', opts)
